server:
  port: 8080
spring:
  application:
    name: docker-container-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        instance-id: ${spring.application.name}-01
        prefer-ip-address: true
        port: ${server.port}
#        ip-address: ${spring.cloud.client.ip-address}


